title: Devaraj's Blog
email: imddevaraj@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My professional blog and portfolio.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://imddevaraj.github.io" # the base hostname & protocol for your site
github_username: imddevaraj
linkedin_username: devarajit

# Profile Information
profile:
  name: "Devaraj Durairaj"
  title: "Technology Leader & Solution Architect"
  phone: "+91 984197-77992"
  birthday: "July 09, 1985"
  location: "Chennai, Tamil Nadu, India"

# theme: minima
plugins:
  - jekyll-feed
